/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package run;

import entities.User;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Vector;
import javax.swing.AbstractButton;

/**
 *
 * @author Windows 10
 */
public class ManagerFrame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public ManagerFrame(String user) {
        initComponents();
        User u = new User();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnStaffManager = new javax.swing.JButton();
        btnCarManager = new javax.swing.JButton();
        btnStatistical = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();
        pnHome = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnStaffManager = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnCarManager = new javax.swing.JPanel();
        pnStatistical = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setSize(new java.awt.Dimension(1024, 768));

        btnHome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/home.png"))); // NOI18N
        btnHome.setText("Trang chủ");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnStaffManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/staff.png"))); // NOI18N
        btnStaffManager.setText("Quản lý nhân viên");
        btnStaffManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffManagerActionPerformed(evt);
            }
        });

        btnCarManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/car.png"))); // NOI18N
        btnCarManager.setText("Quản lý phương tiện");
        btnCarManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarManagerActionPerformed(evt);
            }
        });

        btnStatistical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/statistical.png"))); // NOI18N
        btnStatistical.setText("Thống kê");
        btnStatistical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatisticalActionPerformed(evt);
            }
        });

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/logout.png"))); // NOI18N
        btnLogout.setText("Đăng xuất");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnMenuLayout = new javax.swing.GroupLayout(pnMenu);
        pnMenu.setLayout(pnMenuLayout);
        pnMenuLayout.setHorizontalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMenuLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStaffManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCarManager)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStatistical)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(43, 43, 43))
        );

        pnMenuLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCarManager, btnHome, btnLogout, btnStaffManager, btnStatistical});

        pnMenuLayout.setVerticalGroup(
            pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHome)
                    .addComponent(btnStaffManager)
                    .addComponent(btnCarManager)
                    .addComponent(btnStatistical)
                    .addComponent(btnLogout))
                .addGap(37, 37, 37))
        );

        pnMenuLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLogout, btnStatistical});

        btnHome.setVerticalTextPosition(AbstractButton.BOTTOM);
        btnHome.setHorizontalTextPosition(AbstractButton.CENTER);
        btnStaffManager.setVerticalTextPosition(AbstractButton.BOTTOM);
        btnStaffManager.setHorizontalTextPosition(AbstractButton.CENTER);
        btnStaffManager.setContentAreaFilled(false);
        btnCarManager.setVerticalTextPosition(AbstractButton.BOTTOM);
        btnCarManager.setHorizontalTextPosition(AbstractButton.CENTER);
        btnCarManager.setContentAreaFilled(false);
        btnStatistical.setVerticalTextPosition(AbstractButton.BOTTOM);
        btnStatistical.setHorizontalTextPosition(AbstractButton.CENTER);
        btnStatistical.setContentAreaFilled(false);
        btnLogout.setVerticalTextPosition(AbstractButton.BOTTOM);
        btnLogout.setHorizontalTextPosition(AbstractButton.CENTER);
        btnLogout.setContentAreaFilled(false);

        pnMain.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Avatar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 719, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnHomeLayout = new javax.swing.GroupLayout(pnHome);
        pnHome.setLayout(pnHomeLayout);
        pnHomeLayout.setHorizontalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHomeLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnHomeLayout.setVerticalGroup(
            pnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnMain.add(pnHome, "cardHome");

        jLabel2.setText("label 2");

        javax.swing.GroupLayout pnStaffManagerLayout = new javax.swing.GroupLayout(pnStaffManager);
        pnStaffManager.setLayout(pnStaffManagerLayout);
        pnStaffManagerLayout.setHorizontalGroup(
            pnStaffManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStaffManagerLayout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(jLabel2)
                .addContainerGap(805, Short.MAX_VALUE))
        );
        pnStaffManagerLayout.setVerticalGroup(
            pnStaffManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStaffManagerLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel2)
                .addContainerGap(471, Short.MAX_VALUE))
        );

        pnMain.add(pnStaffManager, "cardStaffManager");

        javax.swing.GroupLayout pnCarManagerLayout = new javax.swing.GroupLayout(pnCarManager);
        pnCarManager.setLayout(pnCarManagerLayout);
        pnCarManagerLayout.setHorizontalGroup(
            pnCarManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        pnCarManagerLayout.setVerticalGroup(
            pnCarManagerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        pnMain.add(pnCarManager, "cardCarManager");

        javax.swing.GroupLayout pnStatisticalLayout = new javax.swing.GroupLayout(pnStatistical);
        pnStatistical.setLayout(pnStatisticalLayout);
        pnStatisticalLayout.setHorizontalGroup(
            pnStatisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        pnStatisticalLayout.setVerticalGroup(
            pnStatisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        pnMain.add(pnStatistical, "cardStatistical");

        jLabel3.setText("Xin chào: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnMenu.setBackground(new java.awt.Color(227, 241, 254));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        ShowCardLayout(pnMain, "cardHome", btnHome);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnStaffManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffManagerActionPerformed
        ShowCardLayout(pnMain, "cardStaffManager", btnStaffManager);
    }//GEN-LAST:event_btnStaffManagerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.dispose();
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCarManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarManagerActionPerformed
        ShowCardLayout(pnMain, "cardCarManager", btnCarManager);
    }//GEN-LAST:event_btnCarManagerActionPerformed

    private void btnStatisticalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatisticalActionPerformed
        ShowCardLayout(pnMain, "cardStatistical", btnStatistical);
    }//GEN-LAST:event_btnStatisticalActionPerformed

    public void ShowCardLayout(javax.swing.JPanel father, String namePanel, javax.swing.JButton button) {
        CardLayout cl = (CardLayout) father.getLayout();
        cl.show(father, namePanel);
        
        Vector<javax.swing.JButton> listB = new Vector<>();
        listB.add(btnHome);
        listB.add(btnStaffManager);
        listB.add(btnCarManager);
        listB.add(btnStatistical);
        for (javax.swing.JButton b : listB) {
            if (b == button) {
                b.setContentAreaFilled(true);
            } else {
                b.setContentAreaFilled(false);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame("admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarManager;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnStaffManager;
    private javax.swing.JButton btnStatistical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnCarManager;
    private javax.swing.JPanel pnHome;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnStaffManager;
    private javax.swing.JPanel pnStatistical;
    // End of variables declaration//GEN-END:variables
}
